### ISSUE TITLE
custom plot template error

### ISSUE THREAD

**Issue by espasov** [jmtsuji/metannotate-analysis#4]
When run this command:(# 4. Print custom plotting template if desired, then exit)
if (print_custom_plot_template == TRUE) {
  barplot_template <- make_barplot_template(hits_collapsed_subset)
  
 
  plotting_template_table_filename <- paste(output_name_general, "_05_custom_plot_template_", tax_rank_to_plot, "_", top_number_to_plot, ".tsv", sep = "")
  write.table(plotting_template_table, file = plotting_template_table_filename, sep = "\t", row.names = F, col.names = T)
  
  stop(paste("Wrote plotting template table to ", plotting_template_table_filename, ".\nPlease fill out desired plotting colours AND put taxa (rows) in the order in which you want them to appear on the plot.\nThen, use this as input for the custom_plot_template variable and set print_custom_plot to TRUE.\nExiting...", sep = ""))
  
}
You get this error: 
Error in is.data.frame(x) : object 'plotting_template_table' not found

Is there someplace in the user set variables to look, to see if something isn't set correctly?

Variables were set as:
HMMs_to_plot <- c("rpoB", "amoA AOA", "amoA AOB", "nxrB")
normalizing_HMM <- "rpoB"
tax_rank_to_plot <- "Species"
top_number_to_plot <- 0.01
output_name_general <- "171016_barplot_species" 
custom_plot_template_filename <-"171016_barplot_species_05_custom_plot_template_Species_0.01_Filled.tsv"

**Comment by jmtsuji** [comment]
Fixed. There was a misnamed variable at the write.table step leftover from a previous version.
